### ISSUE TITLE
MAGE_MODE environment configuration variable leads to inconsistencies

### ISSUE THREAD

**Issue by Vinai** [mageinferno/magento2-docker-compose#39]
The command `bin/magento deploy:mode:set <MODE>` writes the target deploy mode to the file `app/etc/env.php`.  
Unfortunately Magento also supports setting the run mode via environment variables, which easily leads to inconsistent state between commands and web requests being processed.  
For that reason I recommend never using the environment to set the run mode and only use the file `app/etc/env.php`.  
In the current training where we are using the your set of images this inconsistency happens frequently. I would like to suggest removing the setting of MAGE_MODE in the environment.

**Comment by markoshust** [comment]
I'm going to disagree because using environment variables is best-practice within Docker. The filesystem/file located at `app/etc/env.php` should be treated as an ephemeral filesystem, and if the deploy mode is desired to be changed on production or another environment such as staging, one should rather just change an environment variable and never use `bin/magento` to set the deploy mode (or anything else for that matter which can be controlled by environment variables).
